### ISSUE TITLE
Regions 

### ISSUE THREAD

**Issue by Pluteus** [jenkinsci/aws-beanstalk-publisher-plugin#1]
Hi,

I want to deploy the same application in different regions. It is possible to replace/add the dropdown list with a input area that i can insert the region via a parameter? e.g. AWS Region  ${Region} ?

**Comment by DavidTanner** [comment]
I want to leave the option to use a dropdown, but also have a text field.  I haven't spent any time on this lately, I will check it out again, and see if I can get something in the next week or so.
