### ISSUE TITLE
Credentials Not Storing in Job

### ISSUE THREAD

**Issue by rehseboy** [jenkinsci/aws-beanstalk-publisher-plugin#16]
When I create credentials in setup, then select them in my job, then hit "Get Available Applications", it comes back with the message "Missing valid credentials". If I just enter all of my information anyway and try to run the job, it tells me that I have no credentials stored in there. The request to get applications doesn't populate any information other than "awsRegion" in the form.

<img width="863" alt="screen shot 2015-07-28 at 4 10 45 pm" src="https://cloud.githubusercontent.com/assets/313136/8946228/9d83a69c-3543-11e5-9406-ec0f617df7d6.png">

The "Get Available Applications" button works just fine in Jenkins Configuration. I know the creds are valid.

<img width="862" alt="screen shot 2015-07-28 at 4 14 21 pm" src="https://cloud.githubusercontent.com/assets/313136/8946254/d1e4538c-3543-11e5-92e8-51fbac6977ca.png">

**Comment by DavidTanner** [comment]
Found the issue and working on fix/improvement

**Comment by rehseboy** [comment]
Great! I would have tried to debug further, but I don't know Jenkins plugins or how their code is laid out too well. I've fallen back to the other plugin, but I'll definitely switch back to this one once the issue is resolved.

**Comment by DavidTanner** [comment]
So this only affects the lookup from the config page.
