### ISSUE TITLE
AWS Credentials not saving in job config

### ISSUE THREAD

**Issue by fstradiotti** [jenkinsci/aws-beanstalk-publisher-plugin#18]
I have just upgraded the AWS Beanstalk publisher plugin to version 1.5.3 and have noticed an issue that didn't exist before. Previously inside the job configuration I would select from the drop-down menu the "AWS Credentials" that I wanted to use but unfortunately now it looks like the selection will not get saved. 

When i click on the drop-down menu I can see the credentials and I am able to select the desired one. Then i click on "Get Available Applications" and "Get available Environments" and everything works fine, I get the correct list returned. If I then click on save, change page, and then come back to the job configuration, the aws credential i had previously selected is gone. This reflects on the jenkins job failing by giving me error:
```
"No credentials provided for build!!!
ERROR: Build step failed with exception
java.lang.RuntimeException: java.lang.NullPointerException"
```

The workaround for this is typing in manually the credential in the  "AWS Credentials lookup by name". By placing there the full name and credential then it works fine.

**Comment by DavidTanner** [comment]
Fixed in 1.5.4
