### ISSUE TITLE
Version Label Format is unclear

### ISSUE THREAD

**Issue by skmichaelson** [jenkinsci/aws-beanstalk-publisher-plugin#19]
When clicking on the jelly next to the 'Version Label Format', the following instructions appear:

> How to set the version label? For instance, for "${GIT_COMMIT}-${BUILD_TAG}", and with "Key Prefix" set to "myapp/builds/myapp-prod-env/", the S3 Object Key is set to myapp/builds/myapp-prod-env/4b5f7669b3376a1ce504bf7ef8bf7aeee9d21746-myjob-41.zip and the version Label will be 4b5f7669b3376a1ce504bf7ef8bf7aeee9d21746-myjob-41 on AWS EB Application Versions

The first problem I'm finding is that ${BUILD_NUMBER} is not interpolated; rather, it's injected in literally:

```
Environment found (environment id='X-XXXXXXXXXX', name='my-application').
Attempting to update environment to version label '${BUILD_NUMBER}'
'my-application': Attempt 0/5
'my-application': Problem:
com.amazonaws.AmazonServiceException: No Application Version named '"${BUILD_NUMBER}"' found.
(Service: AWSElasticBeanstalk; Status Code: 400; Error Code: InvalidParameterValue; Request ID:
xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)
```

The error implies that I need to enter the name of an <em>existing</em> version, rather than a new one, yet the field is called "format", which makes me think I need to provide some sort of pattern.

**Comment by DavidTanner** [comment]
That field is replacing macros, so the only thing I can think of is that ${BUILD_NUMBER} isn't available at that point.  You can validate this by checking the environment variables of the build.

**Comment by brentsmyth** [comment]
Hey @DavidTanner !  Just so I understand this... Does the "Version Label Format" have to be equal to a filename that has previously been deployed to EB?  I get these errors even when those fields get replaced correctly.

I'm finding that it works if use the last used filename when running `awsebcli`, but not if I try to customize it.  Is there any specific steps to take in order to use a custom format for each build?  Perhaps another Jenkins build process is required before this one?

Thanks!

**Comment by Kabangi** [comment]
@brentsmyth Did you succeed to making this work. Am getting the same error.

**Comment by brentsmyth** [comment]
Hey @Kabangi we ended up using "AWS Elastic Beanstalk Deployment Plugin" https://github.com/jenkinsci/awseb-deployment-plugin

I think this project may be a fork of it?

**Comment by Kabangi** [comment]
@brentsmyth Thanks. Actually I managed to make it work.  Turns out I had to configure S3 and check deploy to S3 option
