### ISSUE TITLE
Get Available Environments with Instance Role Credentials

### ISSUE THREAD

**Issue by gpiper14** [jenkinsci/aws-beanstalk-publisher-plugin#22]
The "Get Available Environments" button in the config page returns an error when using IAM instance roles for credentials. 

Stack Trace produced when clicking on the the "ERROR" link:
>...
>Caused by: java.lang.NullPointerException
>	at org.jenkinsci.plugins.awsbeanstalkpublisher.extensions.envlookup.ByName$DescriptorImpl.getEnvironmentsListAsString(ByName.java:93)
>	at org.jenkinsci.plugins.awsbeanstalkpublisher.extensions.envlookup.ByName$DescriptorImpl.doLoadEnvironments(ByName.java:88)
>...

Plugin Version: 1.5.5

**Comment by jibin-tj** [comment]
I am also having this issue

**Comment by DavidTanner** [comment]
Is fixed in 1.6.0
