### ISSUE TITLE
Deployment with a docker file

### ISSUE THREAD

**Issue by Pinny3** [jenkinsci/aws-beanstalk-publisher-plugin#26]
Hi there,

I've set up Elastic Beanstalk at the AWS Console providing a Dockerfile. 

I wonder how I can use the plugin to schedule a redeploy if a new build has been done. Is there any way? If yes, how?

**Comment by DavidTanner** [comment]
You just need to specify the version name in the plugin.  This is the same as on the aws console.  Don't configure s3,them it will just run the elastic beanstalk command

**Comment by Pinny3** [comment]
Okay, great thanks.
