### ISSUE TITLE
remove prepared zip files

### ISSUE THREAD

**Issue by wdalmut** [jenkinsci/aws-beanstalk-publisher-plugin#4]
Hi,

i see that the plugin prepare the zip file into the `tmp` folder. There is any way to remove those files after a while or after beanstalk deploy?

bests
Walter

**Comment by DavidTanner** [comment]
I have added in a [delete](https://github.com/jenkinsci/aws-beanstalk-publisher-plugin/blob/aws-beanstalk-publisher-plugin-0.1.10/src/main/java/org/jenkinsci/plugins/awsbeanstalkpublisher/AWSEBS3Uploader.java#L114) the tmp file after upload.  You will have to manually delete the extra files from before in your /tmp directory.  I don't want to assume it is safe to just delete everything for you.
